use_default_settings: true

general:
  instance_name: "Team Assistant Search"
  debug: false

search:
  safe_search: 0
  default_lang: "ru"
  formats:
    - html
    - json

server:
  secret_key: "ta-searxng-secret-key-2026"
  bind_address: "0.0.0.0"
  port: 8080
  limiter: false

ui:
  static_use_hash: true
